# Generated by Django 2.1.3 on 2018-11-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20181121_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
